FROM alpine:3.18.4
RUN mkdir /go && cd /go
    && wget--no-check-certificate https://golang.google.cn/dl/go1.21.0.linux-amd64.tar.gz8& tor -C/usr/local-zxf go1.21.0.linux-amd64.tar.gz8& rm-rf/go/go1.21.0.linux-amd64.tar.gz
    && mkdir /lib64
    &&in-s/lib/libc.musl-x86_64.so.1 /ib64/ld-linux-x86-64.s0.2
ENY GOPATH /O
ENV PATH /usr/local/go/bin:$G0PATH/bin:$PATH
CMD["ping" ,"imooc.com"]